### ISSUE TITLE
Are trimmed sequence fasta files generated?

### ISSUE THREAD

**Issue by pdalcinmartins** [kbaseapps/kb-checkV#5]
Hello,

Thanks for implementing CheckV on KBASE!

I am following this protocol: https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-btv8nn9w?step=3
And thus assumed that CheckV would generate the files proviruses.fna and viruses.fna containing trimmed sequences from the step of removing host contamination on proviruses.

I run CheckV v0.0.1 on KBASE and could not find trimmed seq fasta files, but it produced 7 tsv files with all expected output info.
Are such files not generated at the moment? Or is this an error of the app? Or maybe should I look for these files somewhere else, not in the results tab?

Thank you very much for the help,
Paula.

**Comment by Yzm1234** [comment]
Hi Paula,

Thank you for your feedback for CheckV! 

We updated the report and now the result zip file includes 6 files after decompression:
      2 fna files (proviruses.fna, viruses.fna) and 
      4 tsv files (quality_summary.tsv, completeness.tsv,  contamination.tsv, complete_genomes.tsv). 

Please feel free to let us know if you have any further questions, thanks again.

Ziming

**Comment by pdalcinmartins** [comment]
Hi Ziming,

thank you so much for such a quick response and update! 
I just re-run CheckV and got the fna files =D

best wishes,
Paula
